name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  Install node:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Uses Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
      
  Linter:
    needs: [Install node]
    runs-on: ubuntu-latest
    steps:
      - run: npm run eslint

         
  Build:
    needs: [Install node]
    runs-on: ubuntu-latest
    steps:
      - name: Build Valeira
        run: npm run build
            
  Deploy:
    needs: [Install node, Build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
