# Runs linter and potentional test on each pull request and push to master

name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Uses Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci

    - run: npm run eslint
   #- run: npm test There are no test yet :(
    - name: Build Valeira
      run: npm run build
